### ISSUE TITLE
Incorrect processing of <br> tag in the .vue-files

### ISSUE THREAD

**Issue by amorozov** [Polyconseil/easygettext#33] opened 2018-05-22 09:33 UTC
Somewhere between v2.3.0 and v2.4.0 a new behavior of processing tags within translatable messages has been introduced. In v2.3.0 strings like 

    <label for="radio3" v-translate>Some string <br>splitted in two lines</label>
    <label for="radio4" v-translate>Another string with XHTML tag <br/>...continuation</label>

both gave `<br>` in .pot/.po-files:

     msgid "Some string <br>splitted in two lines"
     msgid "Another string with XHTML tag <br>...continuation"

So far so good.

In v.2.4.0 `<br/>` is translated to `<br/>` in the msgids. Unfortunately strings with `<br>` are translated to incorrect msgids like this:

    msgid "Some string <br>splitted in two lines</br>"

The problem with `<br/>` is that it's supported by vue-gettext. Its processing engine splits such strings by inner HTML tags and then joins parts of the message with opening tags to be compatible with previous versions of easygettext. Thus for a string `Another string with XHTML tag <br/>...continuation` it still constructs `Another string with XHTML tag <br>...continuation` and expectedly fails to find it in the dictionary, making impossible to use easygettext-v2.4.0 with vue-gettext.

**Comment by vperron** [comment] 2018-06-29 09:35
Hi, I'm sorry I've been extremely busy lately and didn't even notice your message so far. Do you think you could help finding the root cause ? I'm going on vacation right now and will have a very limited access to Internet, but I'll be pleased to have some more information(or event code) about this when I get back mid July !

**Comment by vperron** [comment] 2018-09-20 08:04
Closing until someone find a renewed interest in this.

**Closed by vperron** 2018-09-20 08:04 UTC
