### ISSUE TITLE
Attributes param also matches tags

### ISSUE THREAD

**Issue by nkostadinov** [Polyconseil/easygettext#26] opened 2017-12-08 13:17 UTC
Currently the attribute parameter cannot distinguish between tags and attributes. I have <v-translate> tags and <span v-translate> and they are both extracted when I provide param  --attribute v-translate

**Comment by vperron** [comment] 2017-12-17 14:19
I'm not sure what you mean by that :)

Can you provide an example ?

All the best,

**Comment by vperron** [comment] 2018-05-09 13:43
Closing as I can't reproduce the issue.

**Closed by vperron** 2018-05-09 13:43 UTC
